packer/roles/workshopper/tasks/main.yml
tasks -
1) pulling the workshopper docker image - osevg/workshopper:0.1
2) installing the systemctl script, systemd-docker binary file and the workshopper config file at required locations
=> adding tasks to workshopper role

cloudformation/qwiklabs-cloudformation.yml
editor-related formatting - added VPCRegion parameter to make stack create complete successfully.
=> add VPCRegion parameter

cloudformation/qwiklabs-cloudformation.yml, packer/roles/workshopper/tasks/main.yml
This PR adds outputs for the hosts IP addresses to be seen in the Qwiklabs interface. This is a temporary measure.
=> Extra outputs

cloudformation/qwiklabs-cloudformation.yml
add runcmd directive to cloud_config_modules to start lab guide automatically
=> add runcmd

cloudformation/qwiklabs-cloudformation.yml
This should set the hostnames properly when runnning 
oc get nodes
=> resolves #22

.gitignore, cloudformation/qwiklabs-cloudformation.yml, packer/roles/idm-install/files/idm-install, packer/roles/idm-install/tasks/main.yml, packer/roles/ocp-installer/files/iptables, packer/roles/ocp-installer/tasks/main.yml, packer/site.yml
IDM reboot actually at launch allowed the idm instance run from 23:40 - 0900
=> Idm with reboot

cloudformation/qwiklabs-cloudformation.yml
AMI to include @dmesser changes
=> ami id change

cloudformation/qwiklabs-cloudformation.yml, labguide/_ocp_admin_testdrive.yaml, labguide/cns-deploy.adoc
- introduced a WaitConditionHandle on GuideNode to declare the lab "ready" after all components have been provisioned and are accessible (addresses #45 )
- introduced a 4th app node in the environment which will serve cluster expansion modules (both OCP and CNS) later
=> Introducing WaitCondition / adding 4th node

cloudformation/qwiklabs-cloudformation.yml, labguide/cns-deploy.adoc, labguide/installation.adoc, labguide/ldap-groupsync.adoc, packer/roles/ansible-host/files/ansible.cfg, packer/roles/ansible-host/tasks/main.yml, packer/roles/authorized-key/tasks/main.yml, packer/roles/inventory-fixup-script/tasks/main.yml, packer/roles/master-cert/tasks/main.yml, packer/roles/registered-host/tasks/main.yml, packer/site.yml, tests/cns-deploy_automation.yml, tests/ldap-groupsync_automation.yaml
Using cloud-user rather than ec2-user for logins
Changed lab guides to reflect new user
=> WIP:Username password

cloudformation/qwiklabs-cloudformation.yml
This will be once the DNS changes are merged
=> use the correct DNS with specific aws account

cloudformation/qwiklabs-cloudformation.yml, packer/roles/idm-install/files/idm-install, packer/roles/inventory-fixup-script/files/inventory_ldap_auth.yml
Fixes the IDM/ldap not being configured at installation
=> Ldap broken

cloudformation/qwiklabs-cloudformation.yml, packer/roles/registry-mirror/tasks/main.yml, packer/roles/registry-mirror/vars/main.yml
=> additional image to ami

cloudformation/qwiklabs-cloudformation.yml
=> add external public ip

.gitignore, cloudformation/qwiklabs-cloudformation.yml, packer/ocp-cns-aio.json, packer/roles/instructor-key/tasks/main.yml, packer/roles/instructor-user/tasks/main.yml, packer/roles/registered-host/tasks/main.yml, packer/site.yml
requires that you run the packer build like this
`packer build -var 'org_id=<org-id>' -var 'activation_key=<key>' -var 'gluster_pool=<pool-id>' -var 'aws_access_key=<aws-key>' -var 'aws_secret_key=<aws-secret>' -var 'vpc_id=<vpc-id>' -var 'subnet_id=<subnet-id>' -var 'instructor_pub_key_file=<absolute-path-to-your-pub-key-file>' ocp-cns-aio.json`
=> add instructor user handling

cloudformation/qwiklabs-cloudformation.yml, packer/roles/instructor-key/tasks/main.yml, packer/site.yml
=> instructor key addition

cloudformation/qwiklabs-cloudformation.yml, packer/roles/registered-host/tasks/main.yml, packer/roles/registered-host/vars/main.yml, packer/roles/registry-mirror/vars/main.yml
=> required images

tests/ci.yaml
This file isn't referenced anywhere so it is good to go.
=> Adds ansible CI file for automated testing of entire lab

ci-test-container/Dockerfile, ci-test-container/script.sh
Stopped using resty because of tty issues and switched to httpie, but forgot to remove resty from the dockerfile.
=> removed resty from the dockerfile

cloudformation/qwiklabs-cloudformation.yml
this time both values are encapsulated (comma-separated) in the QwiklabId parameter from the lab instance in Qwiklab
=> Get GH Repo and Branch name via parameter QwiklabId parameter

cloudformation/qwiklabs-cloudformation.yml
Support events in APAC (starting with OCP Roadshow in Jakarta)
=> Add ap-southeast-1

labguide/app-mgmt-basics.adoc, labguide/cns.adoc, labguide/environment.adoc, labguide/infra-mgmt-basics.adoc, labguide/installation.adoc, labguide/ldap-groupsync.adoc, labguide/skipping-ahead.adoc, labguide/template-quota-limits.adoc
Fix lab guide issue #280 and fix typos
=> Fix issue 280 and fix typos

cloudformation/qwiklabs-cloudformation.yml, labguide/infra-mgmt-basics.adoc, tests/run-module-2-installation.yaml, tests/run-module-6-infra-mgmt.yaml
Reverts openshift/openshift-cns-testdrive#308
=> Revert "Explicitly set storage class for logging and metrics"

labguide/infra-mgmt-basics.adoc
=> resolves #346

cloudformation/qwiklabs-cloudformation.yml, labguide/infra-mgmt-basics.adoc
=> fixes #354

cloudformation/qwiklabs-cloudformation.yml
cherrypicked from https://github.com/openshift/openshift-cns-testdrive/pull/353/commits/a7dcc4282cb21386e04c366ecd6abb8928bbf020
=> resolves #358

labguide/ldap-groupsync.adoc
Needed to correct Prometheus content in ldap-groupsync.adoc to be accurate.
=> Corrected Prometheus content in ldap-groupsync.adoc

labguide/infra-mgmt-basics.adoc
There was an error in the variable name that needs to be corrected. Also INFRA_EXTERNAL_FQDN does not exist.
=> Infra mgmt fix3
